
package au.com.tmha.mos104mi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-10T10:32:09.687+11:00
 * Generated source version: 2.7.18
 * 
 */
public final class MOS104MI_MOS104MIPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.tmha.com.au/MOS104MI", "MOS104MIService");

    private MOS104MI_MOS104MIPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MOS104MIService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MOS104MIService ss = new MOS104MIService(wsdlURL, SERVICE_NAME);
        MOS104MI port = ss.getMOS104MIPort();  
        
        {
        System.out.println("Invoking lstOperElement...");
        au.com.tmha.mos104mi.lstoperelement.LstOperElementCollection _lstOperElement_lstOperElement = new au.com.tmha.mos104mi.lstoperelement.LstOperElementCollection();
        java.util.List<au.com.tmha.mos104mi.lstoperelement.LstOperElementItem> _lstOperElement_lstOperElementLstOperElementItem = new java.util.ArrayList<au.com.tmha.mos104mi.lstoperelement.LstOperElementItem>();
        au.com.tmha.mos104mi.lstoperelement.LstOperElementItem _lstOperElement_lstOperElementLstOperElementItemVal1 = new au.com.tmha.mos104mi.lstoperelement.LstOperElementItem();
        javax.xml.bind.JAXBElement<java.lang.String> _lstOperElement_lstOperElementLstOperElementItemVal1Facility = null;
        _lstOperElement_lstOperElementLstOperElementItemVal1.setFacility(_lstOperElement_lstOperElementLstOperElementItemVal1Facility);
        javax.xml.bind.JAXBElement<java.lang.String> _lstOperElement_lstOperElementLstOperElementItemVal1ProductNumber = null;
        _lstOperElement_lstOperElementLstOperElementItemVal1.setProductNumber(_lstOperElement_lstOperElementLstOperElementItemVal1ProductNumber);
        _lstOperElement_lstOperElementLstOperElementItemVal1.setWorkOrderNumber("WorkOrderNumber681325826");
        _lstOperElement_lstOperElementLstOperElementItemVal1.setOperationNumber(new java.math.BigDecimal("1553630290938096921.4355323820204948801"));
        javax.xml.bind.JAXBElement<java.lang.String> _lstOperElement_lstOperElementLstOperElementItemVal1OperationElementType = null;
        _lstOperElement_lstOperElementLstOperElementItemVal1.setOperationElementType(_lstOperElement_lstOperElementLstOperElementItemVal1OperationElementType);
        _lstOperElement_lstOperElementLstOperElementItem.add(_lstOperElement_lstOperElementLstOperElementItemVal1);
        _lstOperElement_lstOperElement.getLstOperElementItem().addAll(_lstOperElement_lstOperElementLstOperElementItem);
        _lstOperElement_lstOperElement.setMaxRecords(Integer.valueOf(-767617390));
        au.com.tmha.mos104mi.lstoperelement.LstOperElementResponseCollection _lstOperElement__return = port.lstOperElement(_lstOperElement_lstOperElement);
        System.out.println("lstOperElement.result=" + _lstOperElement__return);


        }

        System.exit(0);
    }

}
