package au.com.tmha.mos104mi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.integrationwizards.common.Constants;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-10T10:32:10.067+11:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "MOS104MIService", 
                  wsdlLocation = Constants.localWorkspacePath + "MOS104MI.wsdl",
                  targetNamespace = "http://www.tmha.com.au/MOS104MI") 
public class MOS104MIService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tmha.com.au/MOS104MI", "MOS104MIService");
    public final static QName MOS104MIPort = new QName("http://www.tmha.com.au/MOS104MI", "MOS104MIPort");
    static {
        URL url = null;
        try {
            url = new URL(Constants.localWorkspacePath + "MOS104MI.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MOS104MIService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", Constants.localWorkspacePath + "MOS104MI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MOS104MIService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MOS104MIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MOS104MIService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MOS104MIService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MOS104MIService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MOS104MIService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MOS104MI
     */
    @WebEndpoint(name = "MOS104MIPort")
    public MOS104MI getMOS104MIPort() {
        return super.getPort(MOS104MIPort, MOS104MI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MOS104MI
     */
    @WebEndpoint(name = "MOS104MIPort")
    public MOS104MI getMOS104MIPort(WebServiceFeature... features) {
        return super.getPort(MOS104MIPort, MOS104MI.class, features);
    }

}
