package au.com.tmha.mos104mi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-10T10:32:10.057+11:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.tmha.com.au/MOS104MI", name = "MOS104MI")
@XmlSeeAlso({com.lawson.ws.credentials.ObjectFactory.class, au.com.tmha.mos104mi.lstoperelement.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MOS104MI {

    @WebResult(name = "LstOperElementResponse", targetNamespace = "http://www.tmha.com.au/MOS104MI/LstOperElement", partName = "LstOperElementResponse")
    @WebMethod(operationName = "LstOperElement")
    public au.com.tmha.mos104mi.lstoperelement.LstOperElementResponseCollection lstOperElement(
        @WebParam(partName = "LstOperElement", name = "LstOperElement", targetNamespace = "http://www.tmha.com.au/MOS104MI/LstOperElement")
        au.com.tmha.mos104mi.lstoperelement.LstOperElementCollection lstOperElement
    );
}
