package au.com.retriever.test.barking;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-01-27T10:48:01.674+11:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "https://test.retriever.com.au/barking", name = "RetrieverBarking")
@XmlSeeAlso({ObjectFactory.class})
public interface RetrieverBarking {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "exportStatusUpdates", targetNamespace = "https://test.retriever.com.au/barking", className = "au.com.retriever.test.barking.ExportStatusUpdates")
    @WebMethod
    @ResponseWrapper(localName = "exportStatusUpdatesResponse", targetNamespace = "https://test.retriever.com.au/barking", className = "au.com.retriever.test.barking.ExportStatusUpdatesResponse")
    public au.com.retriever.test.barking.ResultExportStatusUpdates exportStatusUpdates(
        @WebParam(name = "statusUpdate", targetNamespace = "")
        au.com.retriever.test.barking.StatusUpdate statusUpdate
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createJob", targetNamespace = "https://test.retriever.com.au/barking", className = "au.com.retriever.test.barking.CreateJob")
    @WebMethod
    @ResponseWrapper(localName = "createJobResponse", targetNamespace = "https://test.retriever.com.au/barking", className = "au.com.retriever.test.barking.CreateJobResponse")
    public au.com.retriever.test.barking.Result createJob(
        @WebParam(name = "job", targetNamespace = "")
        au.com.retriever.test.barking.Job job
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "exportJobs", targetNamespace = "https://test.retriever.com.au/barking", className = "au.com.retriever.test.barking.ExportJobs")
    @WebMethod
    @ResponseWrapper(localName = "exportJobsResponse", targetNamespace = "https://test.retriever.com.au/barking", className = "au.com.retriever.test.barking.ExportJobsResponse")
    public au.com.retriever.test.barking.ResultExportJobs exportJobs(
        @WebParam(name = "job", targetNamespace = "")
        au.com.retriever.test.barking.ExportJob job
    );
}
