package au.com.tmha.cos100mi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.integrationwizards.common.Constants;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-09T10:11:06.358+11:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "COS100MIService", 
                  wsdlLocation = Constants.localWorkspacePath + "COS100MI.wsdl",
                  targetNamespace = "http://www.tmha.com.au/COS100MI") 
public class COS100MIService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tmha.com.au/COS100MI", "COS100MIService");
    public final static QName COS100MIPort = new QName("http://www.tmha.com.au/COS100MI", "COS100MIPort");
    static {
        URL url = null;
        try {
            url = new URL(Constants.localWorkspacePath + "COS100MI.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(COS100MIService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", Constants.localWorkspacePath + "COS100MI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public COS100MIService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public COS100MIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public COS100MIService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public COS100MIService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public COS100MIService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public COS100MIService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns COS100MI
     */
    @WebEndpoint(name = "COS100MIPort")
    public COS100MI getCOS100MIPort() {
        return super.getPort(COS100MIPort, COS100MI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns COS100MI
     */
    @WebEndpoint(name = "COS100MIPort")
    public COS100MI getCOS100MIPort(WebServiceFeature... features) {
        return super.getPort(COS100MIPort, COS100MI.class, features);
    }

}
