
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package au.com.tmha.cos100mi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-09T10:11:06.322+11:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "COS100MIService",
                      portName = "COS100MIPort",
                      targetNamespace = "http://www.tmha.com.au/COS100MI",
                      wsdlLocation = "file:/C:/Users/User/workspace/JAXWSEclipse/WebContent/WEB-INF/COS100MI.wsdl",
                      endpointInterface = "au.com.tmha.cos100mi.COS100MI")
                      
public class COS100MIImpl implements COS100MI {

    private static final Logger LOG = Logger.getLogger(COS100MIImpl.class.getName());

    /* (non-Javadoc)
     * @see au.com.tmha.cos100mi.COS100MI#lstMCOLines(au.com.tmha.cos100mi.lstmcolines.LstMCOLinesCollection  lstMCOLines )*
     */
    public au.com.tmha.cos100mi.lstmcolines.LstMCOLinesResponseCollection lstMCOLines(au.com.tmha.cos100mi.lstmcolines.LstMCOLinesCollection lstMCOLines) { 
        LOG.info("Executing operation lstMCOLines");
        System.out.println(lstMCOLines);
        try {
            au.com.tmha.cos100mi.lstmcolines.LstMCOLinesResponseCollection _return = new au.com.tmha.cos100mi.lstmcolines.LstMCOLinesResponseCollection();
            java.util.List<au.com.tmha.cos100mi.lstmcolines.LstMCOLinesResponseItem> _returnLstMCOLinesResponseItem = new java.util.ArrayList<au.com.tmha.cos100mi.lstmcolines.LstMCOLinesResponseItem>();
            au.com.tmha.cos100mi.lstmcolines.LstMCOLinesResponseItem _returnLstMCOLinesResponseItemVal1 = new au.com.tmha.cos100mi.lstmcolines.LstMCOLinesResponseItem();
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnLstMCOLinesResponseItemVal1ActualDeliveryDate = null;
            _returnLstMCOLinesResponseItemVal1.setActualDeliveryDate(_returnLstMCOLinesResponseItemVal1ActualDeliveryDate);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnLstMCOLinesResponseItemVal1ActualReceiptDate = null;
            _returnLstMCOLinesResponseItemVal1.setActualReceiptDate(_returnLstMCOLinesResponseItemVal1ActualReceiptDate);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnLstMCOLinesResponseItemVal1PlannedReceiptDate = null;
            _returnLstMCOLinesResponseItemVal1.setPlannedReceiptDate(_returnLstMCOLinesResponseItemVal1PlannedReceiptDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnLstMCOLinesResponseItemVal1ActualReceiptTime = null;
            _returnLstMCOLinesResponseItemVal1.setActualReceiptTime(_returnLstMCOLinesResponseItemVal1ActualReceiptTime);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnLstMCOLinesResponseItemVal1ActualDeliveryTime = null;
            _returnLstMCOLinesResponseItemVal1.setActualDeliveryTime(_returnLstMCOLinesResponseItemVal1ActualDeliveryTime);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnLstMCOLinesResponseItemVal1TransactionNumber = null;
            _returnLstMCOLinesResponseItemVal1.setTransactionNumber(_returnLstMCOLinesResponseItemVal1TransactionNumber);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnLstMCOLinesResponseItemVal1PlannedDeliveryDate = null;
            _returnLstMCOLinesResponseItemVal1.setPlannedDeliveryDate(_returnLstMCOLinesResponseItemVal1PlannedDeliveryDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnLstMCOLinesResponseItemVal1PlannedDeliveryTime = null;
            _returnLstMCOLinesResponseItemVal1.setPlannedDeliveryTime(_returnLstMCOLinesResponseItemVal1PlannedDeliveryTime);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnLstMCOLinesResponseItemVal1PlannedReceiptTime = null;
            _returnLstMCOLinesResponseItemVal1.setPlannedReceiptTime(_returnLstMCOLinesResponseItemVal1PlannedReceiptTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnLstMCOLinesResponseItemVal1Name = null;
            _returnLstMCOLinesResponseItemVal1.setName(_returnLstMCOLinesResponseItemVal1Name);
            javax.xml.bind.JAXBElement<java.lang.String> _returnLstMCOLinesResponseItemVal1ItemNumber = null;
            _returnLstMCOLinesResponseItemVal1.setItemNumber(_returnLstMCOLinesResponseItemVal1ItemNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnLstMCOLinesResponseItemVal1ErrorCode1 = null;
            _returnLstMCOLinesResponseItemVal1.setErrorCode1(_returnLstMCOLinesResponseItemVal1ErrorCode1);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnLstMCOLinesResponseItemVal1ActualStartDate = null;
            _returnLstMCOLinesResponseItemVal1.setActualStartDate(_returnLstMCOLinesResponseItemVal1ActualStartDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnLstMCOLinesResponseItemVal1ActualStartTime = null;
            _returnLstMCOLinesResponseItemVal1.setActualStartTime(_returnLstMCOLinesResponseItemVal1ActualStartTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnLstMCOLinesResponseItemVal1Service = null;
            _returnLstMCOLinesResponseItemVal1.setService(_returnLstMCOLinesResponseItemVal1Service);
            javax.xml.bind.JAXBElement<java.lang.String> _returnLstMCOLinesResponseItemVal1Payer = null;
            _returnLstMCOLinesResponseItemVal1.setPayer(_returnLstMCOLinesResponseItemVal1Payer);
            javax.xml.bind.JAXBElement<java.lang.String> _returnLstMCOLinesResponseItemVal1Supplier = null;
            _returnLstMCOLinesResponseItemVal1.setSupplier(_returnLstMCOLinesResponseItemVal1Supplier);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnLstMCOLinesResponseItemVal1OriginalQuantity = null;
            _returnLstMCOLinesResponseItemVal1.setOriginalQuantity(_returnLstMCOLinesResponseItemVal1OriginalQuantity);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnLstMCOLinesResponseItemVal1OrderLineNumber = null;
            _returnLstMCOLinesResponseItemVal1.setOrderLineNumber(_returnLstMCOLinesResponseItemVal1OrderLineNumber);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnLstMCOLinesResponseItemVal1TransactionQuantityBasicUM = null;
            _returnLstMCOLinesResponseItemVal1.setTransactionQuantityBasicUM(_returnLstMCOLinesResponseItemVal1TransactionQuantityBasicUM);
            _returnLstMCOLinesResponseItem.add(_returnLstMCOLinesResponseItemVal1);
            _return.getLstMCOLinesResponseItem().addAll(_returnLstMCOLinesResponseItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see au.com.tmha.cos100mi.COS100MI#getMCOHead(au.com.tmha.cos100mi.getmcohead.GetMCOHeadCollection  getMCOHead )*
     */
    public au.com.tmha.cos100mi.getmcohead.GetMCOHeadResponseCollection getMCOHead(au.com.tmha.cos100mi.getmcohead.GetMCOHeadCollection getMCOHead) { 
        LOG.info("Executing operation getMCOHead");
        System.out.println(getMCOHead);
        try {
            au.com.tmha.cos100mi.getmcohead.GetMCOHeadResponseCollection _return = new au.com.tmha.cos100mi.getmcohead.GetMCOHeadResponseCollection();
            java.util.List<au.com.tmha.cos100mi.getmcohead.GetMCOHeadResponseItem> _returnGetMCOHeadResponseItem = new java.util.ArrayList<au.com.tmha.cos100mi.getmcohead.GetMCOHeadResponseItem>();
            au.com.tmha.cos100mi.getmcohead.GetMCOHeadResponseItem _returnGetMCOHeadResponseItemVal1 = new au.com.tmha.cos100mi.getmcohead.GetMCOHeadResponseItem();
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMCOHeadResponseItemVal1Customer = null;
            _returnGetMCOHeadResponseItemVal1.setCustomer(_returnGetMCOHeadResponseItemVal1Customer);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMCOHeadResponseItemVal1Facility = null;
            _returnGetMCOHeadResponseItemVal1.setFacility(_returnGetMCOHeadResponseItemVal1Facility);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMCOHeadResponseItemVal1Name = null;
            _returnGetMCOHeadResponseItemVal1.setName(_returnGetMCOHeadResponseItemVal1Name);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetMCOHeadResponseItemVal1OrderDate = null;
            _returnGetMCOHeadResponseItemVal1.setOrderDate(_returnGetMCOHeadResponseItemVal1OrderDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMCOHeadResponseItemVal1Priority = null;
            _returnGetMCOHeadResponseItemVal1.setPriority(_returnGetMCOHeadResponseItemVal1Priority);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMCOHeadResponseItemVal1Product = null;
            _returnGetMCOHeadResponseItemVal1.setProduct(_returnGetMCOHeadResponseItemVal1Product);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMCOHeadResponseItemVal1Responsible = null;
            _returnGetMCOHeadResponseItemVal1.setResponsible(_returnGetMCOHeadResponseItemVal1Responsible);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetMCOHeadResponseItemVal1ActualStartDate = null;
            _returnGetMCOHeadResponseItemVal1.setActualStartDate(_returnGetMCOHeadResponseItemVal1ActualStartDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMCOHeadResponseItemVal1ActualStartTime = null;
            _returnGetMCOHeadResponseItemVal1.setActualStartTime(_returnGetMCOHeadResponseItemVal1ActualStartTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMCOHeadResponseItemVal1PaymentTerms = null;
            _returnGetMCOHeadResponseItemVal1.setPaymentTerms(_returnGetMCOHeadResponseItemVal1PaymentTerms);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetMCOHeadResponseItemVal1PlannedDeliveryDate = null;
            _returnGetMCOHeadResponseItemVal1.setPlannedDeliveryDate(_returnGetMCOHeadResponseItemVal1PlannedDeliveryDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMCOHeadResponseItemVal1PlannedDeliveryTime = null;
            _returnGetMCOHeadResponseItemVal1.setPlannedDeliveryTime(_returnGetMCOHeadResponseItemVal1PlannedDeliveryTime);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetMCOHeadResponseItemVal1ActualDeliveryDate = null;
            _returnGetMCOHeadResponseItemVal1.setActualDeliveryDate(_returnGetMCOHeadResponseItemVal1ActualDeliveryDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMCOHeadResponseItemVal1ActualDeliveryTime = null;
            _returnGetMCOHeadResponseItemVal1.setActualDeliveryTime(_returnGetMCOHeadResponseItemVal1ActualDeliveryTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMCOHeadResponseItemVal1CustomerOrderNumber = null;
            _returnGetMCOHeadResponseItemVal1.setCustomerOrderNumber(_returnGetMCOHeadResponseItemVal1CustomerOrderNumber);
            _returnGetMCOHeadResponseItem.add(_returnGetMCOHeadResponseItemVal1);
            _return.getGetMCOHeadResponseItem().addAll(_returnGetMCOHeadResponseItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
