package au.com.tmha.cos100mi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-09T10:11:06.347+11:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.tmha.com.au/COS100MI", name = "COS100MI")
@XmlSeeAlso({au.com.tmha.cos100mi.lstmcolines.ObjectFactory.class, au.com.tmha.cos100mi.getmcohead.ObjectFactory.class, com.lawson.ws.credentials.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface COS100MI {

    @WebResult(name = "LstMCOLinesResponse", targetNamespace = "http://www.tmha.com.au/COS100MI/LstMCOLines", partName = "LstMCOLinesResponse")
    @WebMethod(operationName = "LstMCOLines")
    public au.com.tmha.cos100mi.lstmcolines.LstMCOLinesResponseCollection lstMCOLines(
        @WebParam(partName = "LstMCOLines", name = "LstMCOLines", targetNamespace = "http://www.tmha.com.au/COS100MI/LstMCOLines")
        au.com.tmha.cos100mi.lstmcolines.LstMCOLinesCollection lstMCOLines
    );

    @WebResult(name = "GetMCOHeadResponse", targetNamespace = "http://www.tmha.com.au/COS100MI/GetMCOHead", partName = "GetMCOHeadResponse")
    @WebMethod(operationName = "GetMCOHead")
    public au.com.tmha.cos100mi.getmcohead.GetMCOHeadResponseCollection getMCOHead(
        @WebParam(partName = "GetMCOHead", name = "GetMCOHead", targetNamespace = "http://www.tmha.com.au/COS100MI/GetMCOHead")
        au.com.tmha.cos100mi.getmcohead.GetMCOHeadCollection getMCOHead
    );
}
