package au.com.tmha.crs610mi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-10T12:24:18.729+11:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.tmha.com.au/CRS610MI", name = "CRS610MI")
@XmlSeeAlso({au.com.tmha.crs610mi.getaddress.ObjectFactory.class, com.lawson.ws.credentials.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CRS610MI {

    @WebResult(name = "GetAddressResponse", targetNamespace = "http://www.tmha.com.au/CRS610MI/GetAddress", partName = "GetAddressResponse")
    @WebMethod(operationName = "GetAddress")
    public au.com.tmha.crs610mi.getaddress.GetAddressResponseCollection getAddress(
        @WebParam(partName = "GetAddress", name = "GetAddress", targetNamespace = "http://www.tmha.com.au/CRS610MI/GetAddress")
        au.com.tmha.crs610mi.getaddress.GetAddressCollection getAddress
    );
}
