
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package au.com.tmha.crs610mi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-10T12:24:18.719+11:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "CRS610MIService",
                      portName = "CRS610MIPort",
                      targetNamespace = "http://www.tmha.com.au/CRS610MI",
                      wsdlLocation = "file:/C:/Users/User/workspace/JAXWSEclipse/WebContent/WEB-INF/CRS610MI.wsdl",
                      endpointInterface = "au.com.tmha.crs610mi.CRS610MI")
                      
public class CRS610MIImpl implements CRS610MI {

    private static final Logger LOG = Logger.getLogger(CRS610MIImpl.class.getName());

    /* (non-Javadoc)
     * @see au.com.tmha.crs610mi.CRS610MI#getAddress(au.com.tmha.crs610mi.getaddress.GetAddressCollection  getAddress )*
     */
    public au.com.tmha.crs610mi.getaddress.GetAddressResponseCollection getAddress(au.com.tmha.crs610mi.getaddress.GetAddressCollection getAddress) { 
        LOG.info("Executing operation getAddress");
        System.out.println(getAddress);
        try {
            au.com.tmha.crs610mi.getaddress.GetAddressResponseCollection _return = new au.com.tmha.crs610mi.getaddress.GetAddressResponseCollection();
            java.util.List<au.com.tmha.crs610mi.getaddress.GetAddressResponseItem> _returnGetAddressResponseItem = new java.util.ArrayList<au.com.tmha.crs610mi.getaddress.GetAddressResponseItem>();
            au.com.tmha.crs610mi.getaddress.GetAddressResponseItem _returnGetAddressResponseItemVal1 = new au.com.tmha.crs610mi.getaddress.GetAddressResponseItem();
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1Country = null;
            _returnGetAddressResponseItemVal1.setCountry(_returnGetAddressResponseItemVal1Country);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1CustomerAddress1 = null;
            _returnGetAddressResponseItemVal1.setCustomerAddress1(_returnGetAddressResponseItemVal1CustomerAddress1);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1CustomerAddress2 = null;
            _returnGetAddressResponseItemVal1.setCustomerAddress2(_returnGetAddressResponseItemVal1CustomerAddress2);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1CustomerAddress3 = null;
            _returnGetAddressResponseItemVal1.setCustomerAddress3(_returnGetAddressResponseItemVal1CustomerAddress3);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1CustomerAddress4 = null;
            _returnGetAddressResponseItemVal1.setCustomerAddress4(_returnGetAddressResponseItemVal1CustomerAddress4);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1CustomerName = null;
            _returnGetAddressResponseItemVal1.setCustomerName(_returnGetAddressResponseItemVal1CustomerName);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1Division = null;
            _returnGetAddressResponseItemVal1.setDivision(_returnGetAddressResponseItemVal1Division);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetAddressResponseItemVal1EANLocationCode = null;
            _returnGetAddressResponseItemVal1.setEANLocationCode(_returnGetAddressResponseItemVal1EANLocationCode);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1AreaState = null;
            _returnGetAddressResponseItemVal1.setAreaState(_returnGetAddressResponseItemVal1AreaState);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1Place = null;
            _returnGetAddressResponseItemVal1.setPlace(_returnGetAddressResponseItemVal1Place);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1TelephoneNumber1 = null;
            _returnGetAddressResponseItemVal1.setTelephoneNumber1(_returnGetAddressResponseItemVal1TelephoneNumber1);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1PostalCode = null;
            _returnGetAddressResponseItemVal1.setPostalCode(_returnGetAddressResponseItemVal1PostalCode);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1TermsText = null;
            _returnGetAddressResponseItemVal1.setTermsText(_returnGetAddressResponseItemVal1TermsText);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1City = null;
            _returnGetAddressResponseItemVal1.setCity(_returnGetAddressResponseItemVal1City);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1YourReference = null;
            _returnGetAddressResponseItemVal1.setYourReference(_returnGetAddressResponseItemVal1YourReference);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetAddressResponseItemVal1AddressCategory = null;
            _returnGetAddressResponseItemVal1.setAddressCategory(_returnGetAddressResponseItemVal1AddressCategory);
            _returnGetAddressResponseItem.add(_returnGetAddressResponseItemVal1);
            _return.getGetAddressResponseItem().addAll(_returnGetAddressResponseItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
