package au.com.tmha.crs610mi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.integrationwizards.common.Constants;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-10T12:24:18.739+11:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "CRS610MIService", 
                  wsdlLocation = Constants.localWorkspacePath + "CRS610MI.wsdl",
                  targetNamespace = "http://www.tmha.com.au/CRS610MI") 
public class CRS610MIService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tmha.com.au/CRS610MI", "CRS610MIService");
    public final static QName CRS610MIPort = new QName("http://www.tmha.com.au/CRS610MI", "CRS610MIPort");
    static {
        URL url = null;
        try {
            url = new URL(Constants.localWorkspacePath + "CRS610MI.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CRS610MIService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", Constants.localWorkspacePath + "CRS610MI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CRS610MIService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CRS610MIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRS610MIService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRS610MIService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRS610MIService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRS610MIService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CRS610MI
     */
    @WebEndpoint(name = "CRS610MIPort")
    public CRS610MI getCRS610MIPort() {
        return super.getPort(CRS610MIPort, CRS610MI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRS610MI
     */
    @WebEndpoint(name = "CRS610MIPort")
    public CRS610MI getCRS610MIPort(WebServiceFeature... features) {
        return super.getPort(CRS610MIPort, CRS610MI.class, features);
    }

}
