
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package au.com.tmha.mos100mi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-05T10:49:39.464+11:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "MOS100MIService",
                      portName = "MOS100MIPort",
                      targetNamespace = "http://www.tmha.com.au/MOS100MI",
                      wsdlLocation = "file:/C:/Users/User/workspace/JAXWSEclipse/WebContent/WEB-INF/MOS100MI.wsdl",
                      endpointInterface = "au.com.tmha.mos100mi.MOS100MI")
                      
public class MOS100MIImpl implements MOS100MI {

    private static final Logger LOG = Logger.getLogger(MOS100MIImpl.class.getName());

    /* (non-Javadoc)
     * @see au.com.tmha.mos100mi.MOS100MI#getMtrl(au.com.tmha.mos100mi.getmtrl.GetMtrlCollection  getMtrl )*
     */
    public au.com.tmha.mos100mi.getmtrl.GetMtrlResponseCollection getMtrl(au.com.tmha.mos100mi.getmtrl.GetMtrlCollection getMtrl) { 
        LOG.info("Executing operation getMtrl");
        System.out.println(getMtrl);
        try {
            au.com.tmha.mos100mi.getmtrl.GetMtrlResponseCollection _return = new au.com.tmha.mos100mi.getmtrl.GetMtrlResponseCollection();
            java.util.List<au.com.tmha.mos100mi.getmtrl.GetMtrlResponseItem> _returnGetMtrlResponseItem = new java.util.ArrayList<au.com.tmha.mos100mi.getmtrl.GetMtrlResponseItem>();
            au.com.tmha.mos100mi.getmtrl.GetMtrlResponseItem _returnGetMtrlResponseItemVal1 = new au.com.tmha.mos100mi.getmtrl.GetMtrlResponseItem();
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1AddressNumber = null;
            _returnGetMtrlResponseItemVal1.setAddressNumber(_returnGetMtrlResponseItemVal1AddressNumber);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1AddressType = null;
            _returnGetMtrlResponseItemVal1.setAddressType(_returnGetMtrlResponseItemVal1AddressType);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1LotNumber = null;
            _returnGetMtrlResponseItemVal1.setLotNumber(_returnGetMtrlResponseItemVal1LotNumber);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1Quantity = null;
            _returnGetMtrlResponseItemVal1.setQuantity(_returnGetMtrlResponseItemVal1Quantity);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1FromWarehouse = null;
            _returnGetMtrlResponseItemVal1.setFromWarehouse(_returnGetMtrlResponseItemVal1FromWarehouse);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1LineType = null;
            _returnGetMtrlResponseItemVal1.setLineType(_returnGetMtrlResponseItemVal1LineType);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1Priority = null;
            _returnGetMtrlResponseItemVal1.setPriority(_returnGetMtrlResponseItemVal1Priority);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1ProductNumber = null;
            _returnGetMtrlResponseItemVal1.setProductNumber(_returnGetMtrlResponseItemVal1ProductNumber);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1ReservedQuantity = null;
            _returnGetMtrlResponseItemVal1.setReservedQuantity(_returnGetMtrlResponseItemVal1ReservedQuantity);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1SalesPrice = null;
            _returnGetMtrlResponseItemVal1.setSalesPrice(_returnGetMtrlResponseItemVal1SalesPrice);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1ReceivedQuantity = null;
            _returnGetMtrlResponseItemVal1.setReceivedQuantity(_returnGetMtrlResponseItemVal1ReceivedQuantity);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1OrderType = null;
            _returnGetMtrlResponseItemVal1.setOrderType(_returnGetMtrlResponseItemVal1OrderType);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1Warehouse = null;
            _returnGetMtrlResponseItemVal1.setWarehouse(_returnGetMtrlResponseItemVal1Warehouse);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1Location = null;
            _returnGetMtrlResponseItemVal1.setLocation(_returnGetMtrlResponseItemVal1Location);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1MaterialStatus = null;
            _returnGetMtrlResponseItemVal1.setMaterialStatus(_returnGetMtrlResponseItemVal1MaterialStatus);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1ReportingNumber = null;
            _returnGetMtrlResponseItemVal1.setReportingNumber(_returnGetMtrlResponseItemVal1ReportingNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1ToLocation = null;
            _returnGetMtrlResponseItemVal1.setToLocation(_returnGetMtrlResponseItemVal1ToLocation);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1SupplierNumber = null;
            _returnGetMtrlResponseItemVal1.setSupplierNumber(_returnGetMtrlResponseItemVal1SupplierNumber);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1ReportedQuantity = null;
            _returnGetMtrlResponseItemVal1.setReportedQuantity(_returnGetMtrlResponseItemVal1ReportedQuantity);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetMtrlResponseItemVal1ReportingDate = null;
            _returnGetMtrlResponseItemVal1.setReportingDate(_returnGetMtrlResponseItemVal1ReportingDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1ReferenceOrderLine = null;
            _returnGetMtrlResponseItemVal1.setReferenceOrderLine(_returnGetMtrlResponseItemVal1ReferenceOrderLine);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1ReferenceOrderNumber = null;
            _returnGetMtrlResponseItemVal1.setReferenceOrderNumber(_returnGetMtrlResponseItemVal1ReferenceOrderNumber);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1ReferenceOrderCategory = null;
            _returnGetMtrlResponseItemVal1.setReferenceOrderCategory(_returnGetMtrlResponseItemVal1ReferenceOrderCategory);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1PlannedOrder = null;
            _returnGetMtrlResponseItemVal1.setPlannedOrder(_returnGetMtrlResponseItemVal1PlannedOrder);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1WorkCenter = null;
            _returnGetMtrlResponseItemVal1.setWorkCenter(_returnGetMtrlResponseItemVal1WorkCenter);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1OperationNumber = null;
            _returnGetMtrlResponseItemVal1.setOperationNumber(_returnGetMtrlResponseItemVal1OperationNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetMtrlResponseItemVal1Text = null;
            _returnGetMtrlResponseItemVal1.setText(_returnGetMtrlResponseItemVal1Text);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetMtrlResponseItemVal1AllocatedQuantityBasicUM = null;
            _returnGetMtrlResponseItemVal1.setAllocatedQuantityBasicUM(_returnGetMtrlResponseItemVal1AllocatedQuantityBasicUM);
            _returnGetMtrlResponseItem.add(_returnGetMtrlResponseItemVal1);
            _return.getGetMtrlResponseItem().addAll(_returnGetMtrlResponseItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see au.com.tmha.mos100mi.MOS100MI#getOp(au.com.tmha.mos100mi.getop.GetOpCollection  getOp )*
     */
    public au.com.tmha.mos100mi.getop.GetOpResponseCollection getOp(au.com.tmha.mos100mi.getop.GetOpCollection getOp) { 
        LOG.info("Executing operation getOp");
        System.out.println(getOp);
        try {
            au.com.tmha.mos100mi.getop.GetOpResponseCollection _return = new au.com.tmha.mos100mi.getop.GetOpResponseCollection();
            java.util.List<au.com.tmha.mos100mi.getop.GetOpResponseItem> _returnGetOpResponseItem = new java.util.ArrayList<au.com.tmha.mos100mi.getop.GetOpResponseItem>();
            au.com.tmha.mos100mi.getop.GetOpResponseItem _returnGetOpResponseItemVal1 = new au.com.tmha.mos100mi.getop.GetOpResponseItem();
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1LotNumber = null;
            _returnGetOpResponseItemVal1.setLotNumber(_returnGetOpResponseItemVal1LotNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1CostCenter = null;
            _returnGetOpResponseItemVal1.setCostCenter(_returnGetOpResponseItemVal1CostCenter);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1ErrorCode2 = null;
            _returnGetOpResponseItemVal1.setErrorCode2(_returnGetOpResponseItemVal1ErrorCode2);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1ErrorCode3 = null;
            _returnGetOpResponseItemVal1.setErrorCode3(_returnGetOpResponseItemVal1ErrorCode3);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1ErrorCode1 = null;
            _returnGetOpResponseItemVal1.setErrorCode1(_returnGetOpResponseItemVal1ErrorCode1);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetOpResponseItemVal1FinishDate = null;
            _returnGetOpResponseItemVal1.setFinishDate(_returnGetOpResponseItemVal1FinishDate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1ItemNumber = null;
            _returnGetOpResponseItemVal1.setItemNumber(_returnGetOpResponseItemVal1ItemNumber);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1ManufacturedQuantity = null;
            _returnGetOpResponseItemVal1.setManufacturedQuantity(_returnGetOpResponseItemVal1ManufacturedQuantity);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1StartTime = null;
            _returnGetOpResponseItemVal1.setStartTime(_returnGetOpResponseItemVal1StartTime);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1FinishTime = null;
            _returnGetOpResponseItemVal1.setFinishTime(_returnGetOpResponseItemVal1FinishTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1OperationDescription = null;
            _returnGetOpResponseItemVal1.setOperationDescription(_returnGetOpResponseItemVal1OperationDescription);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1WorkCenter = null;
            _returnGetOpResponseItemVal1.setWorkCenter(_returnGetOpResponseItemVal1WorkCenter);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1PlanningArea = null;
            _returnGetOpResponseItemVal1.setPlanningArea(_returnGetOpResponseItemVal1PlanningArea);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetOpResponseItemVal1ReportingDate = null;
            _returnGetOpResponseItemVal1.setReportingDate(_returnGetOpResponseItemVal1ReportingDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1ReferenceOrderLine = null;
            _returnGetOpResponseItemVal1.setReferenceOrderLine(_returnGetOpResponseItemVal1ReferenceOrderLine);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1ReportingTime = null;
            _returnGetOpResponseItemVal1.setReportingTime(_returnGetOpResponseItemVal1ReportingTime);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1SalesPrice = null;
            _returnGetOpResponseItemVal1.setSalesPrice(_returnGetOpResponseItemVal1SalesPrice);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1Service = null;
            _returnGetOpResponseItemVal1.setService(_returnGetOpResponseItemVal1Service);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetOpResponseItemVal1StartDate = null;
            _returnGetOpResponseItemVal1.setStartDate(_returnGetOpResponseItemVal1StartDate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1TextLine1 = null;
            _returnGetOpResponseItemVal1.setTextLine1(_returnGetOpResponseItemVal1TextLine1);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1TextLine2 = null;
            _returnGetOpResponseItemVal1.setTextLine2(_returnGetOpResponseItemVal1TextLine2);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1TextIdentity = null;
            _returnGetOpResponseItemVal1.setTextIdentity(_returnGetOpResponseItemVal1TextIdentity);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1Status = null;
            _returnGetOpResponseItemVal1.setStatus(_returnGetOpResponseItemVal1Status);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1ReportingNumber = null;
            _returnGetOpResponseItemVal1.setReportingNumber(_returnGetOpResponseItemVal1ReportingNumber);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1SupplierNumber = null;
            _returnGetOpResponseItemVal1.setSupplierNumber(_returnGetOpResponseItemVal1SupplierNumber);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetOpResponseItemVal1ActualStartDate = null;
            _returnGetOpResponseItemVal1.setActualStartDate(_returnGetOpResponseItemVal1ActualStartDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1ActualStartTime = null;
            _returnGetOpResponseItemVal1.setActualStartTime(_returnGetOpResponseItemVal1ActualStartTime);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1ActualFinishTime = null;
            _returnGetOpResponseItemVal1.setActualFinishTime(_returnGetOpResponseItemVal1ActualFinishTime);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetOpResponseItemVal1EntryDate = null;
            _returnGetOpResponseItemVal1.setEntryDate(_returnGetOpResponseItemVal1EntryDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1EntryTime = null;
            _returnGetOpResponseItemVal1.setEntryTime(_returnGetOpResponseItemVal1EntryTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetOpResponseItemVal1ProductNumber = null;
            _returnGetOpResponseItemVal1.setProductNumber(_returnGetOpResponseItemVal1ProductNumber);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1UnitPrice = null;
            _returnGetOpResponseItemVal1.setUnitPrice(_returnGetOpResponseItemVal1UnitPrice);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1OperationStarted = null;
            _returnGetOpResponseItemVal1.setOperationStarted(_returnGetOpResponseItemVal1OperationStarted);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetOpResponseItemVal1ActualFinishDate = null;
            _returnGetOpResponseItemVal1.setActualFinishDate(_returnGetOpResponseItemVal1ActualFinishDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetOpResponseItemVal1Priority = null;
            _returnGetOpResponseItemVal1.setPriority(_returnGetOpResponseItemVal1Priority);
            _returnGetOpResponseItem.add(_returnGetOpResponseItemVal1);
            _return.getGetOpResponseItem().addAll(_returnGetOpResponseItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see au.com.tmha.mos100mi.MOS100MI#get(au.com.tmha.mos100mi.get.GetCollection  get )*
     */
    public au.com.tmha.mos100mi.get.GetResponseCollection get(au.com.tmha.mos100mi.get.GetCollection get) { 
        LOG.info("Executing operation get");
        System.out.println(get);
        try {
            au.com.tmha.mos100mi.get.GetResponseCollection _return = new au.com.tmha.mos100mi.get.GetResponseCollection();
            java.util.List<au.com.tmha.mos100mi.get.GetResponseItem> _returnGetResponseItem = new java.util.ArrayList<au.com.tmha.mos100mi.get.GetResponseItem>();
            au.com.tmha.mos100mi.get.GetResponseItem _returnGetResponseItemVal1 = new au.com.tmha.mos100mi.get.GetResponseItem();
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1Lotnumber = null;
            _returnGetResponseItemVal1.setLotnumber(_returnGetResponseItemVal1Lotnumber);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetResponseItemVal1BreakdownDate = null;
            _returnGetResponseItemVal1.setBreakdownDate(_returnGetResponseItemVal1BreakdownDate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1UserdefinedField1Item = null;
            _returnGetResponseItemVal1.setUserdefinedField1Item(_returnGetResponseItemVal1UserdefinedField1Item);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1UserdefinedField2Item = null;
            _returnGetResponseItemVal1.setUserdefinedField2Item(_returnGetResponseItemVal1UserdefinedField2Item);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1UserdefinedField3Item = null;
            _returnGetResponseItemVal1.setUserdefinedField3Item(_returnGetResponseItemVal1UserdefinedField3Item);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1UserdefinedField4Item = null;
            _returnGetResponseItemVal1.setUserdefinedField4Item(_returnGetResponseItemVal1UserdefinedField4Item);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1UserdefinedField5Item = null;
            _returnGetResponseItemVal1.setUserdefinedField5Item(_returnGetResponseItemVal1UserdefinedField5Item);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1MainProduct = null;
            _returnGetResponseItemVal1.setMainProduct(_returnGetResponseItemVal1MainProduct);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1ProductDescription = null;
            _returnGetResponseItemVal1.setProductDescription(_returnGetResponseItemVal1ProductDescription);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1PlannedFinishTime = null;
            _returnGetResponseItemVal1.setPlannedFinishTime(_returnGetResponseItemVal1PlannedFinishTime);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1PlannedStartTime = null;
            _returnGetResponseItemVal1.setPlannedStartTime(_returnGetResponseItemVal1PlannedStartTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1OrderType = null;
            _returnGetResponseItemVal1.setOrderType(_returnGetResponseItemVal1OrderType);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1OrderedQuantity = null;
            _returnGetResponseItemVal1.setOrderedQuantity(_returnGetResponseItemVal1OrderedQuantity);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1Priority = null;
            _returnGetResponseItemVal1.setPriority(_returnGetResponseItemVal1Priority);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetResponseItemVal1EntryDate = null;
            _returnGetResponseItemVal1.setEntryDate(_returnGetResponseItemVal1EntryDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1EntryTime = null;
            _returnGetResponseItemVal1.setEntryTime(_returnGetResponseItemVal1EntryTime);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1ReferenceOrderCategory = null;
            _returnGetResponseItemVal1.setReferenceOrderCategory(_returnGetResponseItemVal1ReferenceOrderCategory);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1ReferenceOrderLine = null;
            _returnGetResponseItemVal1.setReferenceOrderLine(_returnGetResponseItemVal1ReferenceOrderLine);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1ReferenceOrderNumber = null;
            _returnGetResponseItemVal1.setReferenceOrderNumber(_returnGetResponseItemVal1ReferenceOrderNumber);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1LineSuffix = null;
            _returnGetResponseItemVal1.setLineSuffix(_returnGetResponseItemVal1LineSuffix);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetResponseItemVal1ReportingDate = null;
            _returnGetResponseItemVal1.setReportingDate(_returnGetResponseItemVal1ReportingDate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1Requester = null;
            _returnGetResponseItemVal1.setRequester(_returnGetResponseItemVal1Requester);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetResponseItemVal1RequestedFinishDate = null;
            _returnGetResponseItemVal1.setRequestedFinishDate(_returnGetResponseItemVal1RequestedFinishDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1RequestedFinishTime = null;
            _returnGetResponseItemVal1.setRequestedFinishTime(_returnGetResponseItemVal1RequestedFinishTime);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetResponseItemVal1RequestedStartDate = null;
            _returnGetResponseItemVal1.setRequestedStartDate(_returnGetResponseItemVal1RequestedStartDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1RequestedStartTime = null;
            _returnGetResponseItemVal1.setRequestedStartTime(_returnGetResponseItemVal1RequestedStartTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1UserDefinedField1 = null;
            _returnGetResponseItemVal1.setUserDefinedField1(_returnGetResponseItemVal1UserDefinedField1);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1UserDefinedField2 = null;
            _returnGetResponseItemVal1.setUserDefinedField2(_returnGetResponseItemVal1UserDefinedField2);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1UserDefinedField3 = null;
            _returnGetResponseItemVal1.setUserDefinedField3(_returnGetResponseItemVal1UserDefinedField3);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1UserDefinedField4 = null;
            _returnGetResponseItemVal1.setUserDefinedField4(_returnGetResponseItemVal1UserDefinedField4);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1UserDefinedField5 = null;
            _returnGetResponseItemVal1.setUserDefinedField5(_returnGetResponseItemVal1UserDefinedField5);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1UserDefinedField6 = null;
            _returnGetResponseItemVal1.setUserDefinedField6(_returnGetResponseItemVal1UserDefinedField6);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1StructureType = null;
            _returnGetResponseItemVal1.setStructureType(_returnGetResponseItemVal1StructureType);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1Service = null;
            _returnGetResponseItemVal1.setService(_returnGetResponseItemVal1Service);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1EarliestStartTime = null;
            _returnGetResponseItemVal1.setEarliestStartTime(_returnGetResponseItemVal1EarliestStartTime);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1DueTime = null;
            _returnGetResponseItemVal1.setDueTime(_returnGetResponseItemVal1DueTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1TextLine = null;
            _returnGetResponseItemVal1.setTextLine(_returnGetResponseItemVal1TextLine);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1TextLineTXT2 = null;
            _returnGetResponseItemVal1.setTextLineTXT2(_returnGetResponseItemVal1TextLineTXT2);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1Warehouse = null;
            _returnGetResponseItemVal1.setWarehouse(_returnGetResponseItemVal1Warehouse);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1Status = null;
            _returnGetResponseItemVal1.setStatus(_returnGetResponseItemVal1Status);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1ReportingTime = null;
            _returnGetResponseItemVal1.setReportingTime(_returnGetResponseItemVal1ReportingTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1WorkCenterResource = null;
            _returnGetResponseItemVal1.setWorkCenterResource(_returnGetResponseItemVal1WorkCenterResource);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1ManufacturedQuantity = null;
            _returnGetResponseItemVal1.setManufacturedQuantity(_returnGetResponseItemVal1ManufacturedQuantity);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetResponseItemVal1PlannedFinishDate = null;
            _returnGetResponseItemVal1.setPlannedFinishDate(_returnGetResponseItemVal1PlannedFinishDate);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetResponseItemVal1DueDate = null;
            _returnGetResponseItemVal1.setDueDate(_returnGetResponseItemVal1DueDate);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1BreakDownTime = null;
            _returnGetResponseItemVal1.setBreakDownTime(_returnGetResponseItemVal1BreakDownTime);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1AddressNumber = null;
            _returnGetResponseItemVal1.setAddressNumber(_returnGetResponseItemVal1AddressNumber);
            javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnGetResponseItemVal1PlannedStartDate = null;
            _returnGetResponseItemVal1.setPlannedStartDate(_returnGetResponseItemVal1PlannedStartDate);
            javax.xml.bind.JAXBElement<java.lang.String> _returnGetResponseItemVal1ActionMessage = null;
            _returnGetResponseItemVal1.setActionMessage(_returnGetResponseItemVal1ActionMessage);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1AddressType = null;
            _returnGetResponseItemVal1.setAddressType(_returnGetResponseItemVal1AddressType);
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnGetResponseItemVal1ConfigurationNumber = null;
            _returnGetResponseItemVal1.setConfigurationNumber(_returnGetResponseItemVal1ConfigurationNumber);
            _returnGetResponseItem.add(_returnGetResponseItemVal1);
            _return.getGetResponseItem().addAll(_returnGetResponseItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
