
package au.com.tmha.mos100mi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-05T10:49:39.410+11:00
 * Generated source version: 2.7.18
 * 
 */
public final class MOS100MI_MOS100MIPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.tmha.com.au/MOS100MI", "MOS100MIService");

    private MOS100MI_MOS100MIPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MOS100MIService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MOS100MIService ss = new MOS100MIService(wsdlURL, SERVICE_NAME);
        MOS100MI port = ss.getMOS100MIPort();  
        
        {
        System.out.println("Invoking getMtrl...");
        au.com.tmha.mos100mi.getmtrl.GetMtrlCollection _getMtrl_getMtrl = new au.com.tmha.mos100mi.getmtrl.GetMtrlCollection();
        java.util.List<au.com.tmha.mos100mi.getmtrl.GetMtrlItem> _getMtrl_getMtrlGetMtrlItem = new java.util.ArrayList<au.com.tmha.mos100mi.getmtrl.GetMtrlItem>();
        au.com.tmha.mos100mi.getmtrl.GetMtrlItem _getMtrl_getMtrlGetMtrlItemVal1 = new au.com.tmha.mos100mi.getmtrl.GetMtrlItem();
        _getMtrl_getMtrlGetMtrlItemVal1.setWorkOrderNumber("WorkOrderNumber-730728146");
        _getMtrl_getMtrlGetMtrlItemVal1.setSequenceNumber(new java.math.BigDecimal("5729713621336103381.6762563252665558615"));
        javax.xml.bind.JAXBElement<java.math.BigDecimal> _getMtrl_getMtrlGetMtrlItemVal1RetriveCost = null;
        _getMtrl_getMtrlGetMtrlItemVal1.setRetriveCost(_getMtrl_getMtrlGetMtrlItemVal1RetriveCost);
        javax.xml.bind.JAXBElement<java.math.BigDecimal> _getMtrl_getMtrlGetMtrlItemVal1YesNo = null;
        _getMtrl_getMtrlGetMtrlItemVal1.setYesNo(_getMtrl_getMtrlGetMtrlItemVal1YesNo);
        _getMtrl_getMtrlGetMtrlItem.add(_getMtrl_getMtrlGetMtrlItemVal1);
        _getMtrl_getMtrl.getGetMtrlItem().addAll(_getMtrl_getMtrlGetMtrlItem);
        _getMtrl_getMtrl.setMaxRecords(Integer.valueOf(-184097449));
        au.com.tmha.mos100mi.getmtrl.GetMtrlResponseCollection _getMtrl__return = port.getMtrl(_getMtrl_getMtrl);
        System.out.println("getMtrl.result=" + _getMtrl__return);


        }
        {
        System.out.println("Invoking getOp...");
        au.com.tmha.mos100mi.getop.GetOpCollection _getOp_getOp = new au.com.tmha.mos100mi.getop.GetOpCollection();
        java.util.List<au.com.tmha.mos100mi.getop.GetOpItem> _getOp_getOpGetOpItem = new java.util.ArrayList<au.com.tmha.mos100mi.getop.GetOpItem>();
        au.com.tmha.mos100mi.getop.GetOpItem _getOp_getOpGetOpItemVal1 = new au.com.tmha.mos100mi.getop.GetOpItem();
        _getOp_getOpGetOpItemVal1.setWorkOrderNumber("WorkOrderNumber1243764976");
        _getOp_getOpGetOpItemVal1.setOperationNumber(new java.math.BigDecimal("6603113317059361687.5364278067777766052"));
        javax.xml.bind.JAXBElement<java.math.BigDecimal> _getOp_getOpGetOpItemVal1RetriveEstimatedCost = null;
        _getOp_getOpGetOpItemVal1.setRetriveEstimatedCost(_getOp_getOpGetOpItemVal1RetriveEstimatedCost);
        javax.xml.bind.JAXBElement<java.math.BigDecimal> _getOp_getOpGetOpItemVal1YesNo = null;
        _getOp_getOpGetOpItemVal1.setYesNo(_getOp_getOpGetOpItemVal1YesNo);
        _getOp_getOpGetOpItem.add(_getOp_getOpGetOpItemVal1);
        _getOp_getOp.getGetOpItem().addAll(_getOp_getOpGetOpItem);
        _getOp_getOp.setMaxRecords(Integer.valueOf(-2045524483));
        au.com.tmha.mos100mi.getop.GetOpResponseCollection _getOp__return = port.getOp(_getOp_getOp);
        System.out.println("getOp.result=" + _getOp__return);


        }
        {
        System.out.println("Invoking get...");
        au.com.tmha.mos100mi.get.GetCollection _get_get = new au.com.tmha.mos100mi.get.GetCollection();
        java.util.List<au.com.tmha.mos100mi.get.GetItem> _get_getGetItem = new java.util.ArrayList<au.com.tmha.mos100mi.get.GetItem>();
        au.com.tmha.mos100mi.get.GetItem _get_getGetItemVal1 = new au.com.tmha.mos100mi.get.GetItem();
        javax.xml.bind.JAXBElement<java.math.BigDecimal> _get_getGetItemVal1Company = null;
        _get_getGetItemVal1.setCompany(_get_getGetItemVal1Company);
        _get_getGetItemVal1.setFacility("Facility2130161043");
        _get_getGetItemVal1.setProductNumber("ProductNumber1293112417");
        _get_getGetItemVal1.setManufacturingOrderNumber("ManufacturingOrderNumber-273065248");
        javax.xml.bind.JAXBElement<java.lang.String> _get_getGetItemVal1PlanningArea = null;
        _get_getGetItemVal1.setPlanningArea(_get_getGetItemVal1PlanningArea);
        _get_getGetItem.add(_get_getGetItemVal1);
        _get_get.getGetItem().addAll(_get_getGetItem);
        _get_get.setMaxRecords(Integer.valueOf(-931574807));
        au.com.tmha.mos100mi.get.GetResponseCollection _get__return = port.get(_get_get);
        System.out.println("get.result=" + _get__return);


        }

        System.exit(0);
    }

}
