package au.com.tmha.mos100mi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-05T10:49:39.487+11:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.tmha.com.au/MOS100MI", name = "MOS100MI")
@XmlSeeAlso({au.com.tmha.mos100mi.get.ObjectFactory.class, au.com.tmha.mos100mi.getmtrl.ObjectFactory.class, com.lawson.ws.credentials.ObjectFactory.class, au.com.tmha.mos100mi.getop.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MOS100MI {

    @WebResult(name = "GetMtrlResponse", targetNamespace = "http://www.tmha.com.au/MOS100MI/GetMtrl", partName = "GetMtrlResponse")
    @WebMethod(operationName = "GetMtrl")
    public au.com.tmha.mos100mi.getmtrl.GetMtrlResponseCollection getMtrl(
        @WebParam(partName = "GetMtrl", name = "GetMtrl", targetNamespace = "http://www.tmha.com.au/MOS100MI/GetMtrl")
        au.com.tmha.mos100mi.getmtrl.GetMtrlCollection getMtrl
    );

    @WebResult(name = "GetOpResponse", targetNamespace = "http://www.tmha.com.au/MOS100MI/GetOp", partName = "GetOpResponse")
    @WebMethod(operationName = "GetOp")
    public au.com.tmha.mos100mi.getop.GetOpResponseCollection getOp(
        @WebParam(partName = "GetOp", name = "GetOp", targetNamespace = "http://www.tmha.com.au/MOS100MI/GetOp")
        au.com.tmha.mos100mi.getop.GetOpCollection getOp
    );

    @WebResult(name = "GetResponse", targetNamespace = "http://www.tmha.com.au/MOS100MI/Get", partName = "GetResponse")
    @WebMethod(operationName = "Get")
    public au.com.tmha.mos100mi.get.GetResponseCollection get(
        @WebParam(partName = "Get", name = "Get", targetNamespace = "http://www.tmha.com.au/MOS100MI/Get")
        au.com.tmha.mos100mi.get.GetCollection get
    );
}
