package au.com.tmha.mos195mi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-12T12:42:49.048+11:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "MOS195MIService", 
                  wsdlLocation = "file:/C:/Users/User/workspace/JAXWSEclipse/WebContent/WEB-INF/MOS195MI.wsdl",
                  targetNamespace = "http://www.tmha.com.au/MOS195MI") 
public class MOS195MIService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tmha.com.au/MOS195MI", "MOS195MIService");
    public final static QName MOS195MIPort = new QName("http://www.tmha.com.au/MOS195MI", "MOS195MIPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/User/workspace/JAXWSEclipse/WebContent/WEB-INF/MOS195MI.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MOS195MIService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/User/workspace/JAXWSEclipse/WebContent/WEB-INF/MOS195MI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MOS195MIService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MOS195MIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MOS195MIService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MOS195MIService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MOS195MIService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MOS195MIService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MOS195MI
     */
    @WebEndpoint(name = "MOS195MIPort")
    public MOS195MI getMOS195MIPort() {
        return super.getPort(MOS195MIPort, MOS195MI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MOS195MI
     */
    @WebEndpoint(name = "MOS195MIPort")
    public MOS195MI getMOS195MIPort(WebServiceFeature... features) {
        return super.getPort(MOS195MIPort, MOS195MI.class, features);
    }

}
