
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package au.com.tmha.mos057mi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-24T13:10:05.858+11:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "MOS057MIService",
                      portName = "MOS057MIPort",
                      targetNamespace = "http://www.tmha.com.au/MOS057MI",
                      wsdlLocation = "file:/C:/Users/User/workspace/JAXWSEclipse/WebContent/WEB-INF/MOS057MI.wsdl",
                      endpointInterface = "au.com.tmha.mos057mi.MOS057MI")
                      
public class MOS057MIImpl implements MOS057MI {

    private static final Logger LOG = Logger.getLogger(MOS057MIImpl.class.getName());

    /* (non-Javadoc)
     * @see au.com.tmha.mos057mi.MOS057MI#add(au.com.tmha.mos057mi.add.AddCollection  add )*
     */
    public au.com.tmha.mos057mi.add.AddResponseCollection add(au.com.tmha.mos057mi.add.AddCollection add) { 
        LOG.info("Executing operation add");
        System.out.println(add);
        try {
            au.com.tmha.mos057mi.add.AddResponseCollection _return = new au.com.tmha.mos057mi.add.AddResponseCollection();
            java.util.List<au.com.tmha.mos057mi.add.AddResponseItem> _returnAddResponseItem = new java.util.ArrayList<au.com.tmha.mos057mi.add.AddResponseItem>();
            au.com.tmha.mos057mi.add.AddResponseItem _returnAddResponseItemVal1 = new au.com.tmha.mos057mi.add.AddResponseItem();
            javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnAddResponseItemVal1SequenceNumber = null;
            _returnAddResponseItemVal1.setSequenceNumber(_returnAddResponseItemVal1SequenceNumber);
            _returnAddResponseItem.add(_returnAddResponseItemVal1);
            _return.getAddResponseItem().addAll(_returnAddResponseItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
