package au.com.tmha.mos070mi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.integrationwizards.common.Constants;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-24T10:22:00.067+11:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "MOS070MIService", 
                  wsdlLocation = Constants.localWorkspacePath + "MOS070MI.wsdl",
                  targetNamespace = "http://www.tmha.com.au/MOS070MI") 
public class MOS070MIService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tmha.com.au/MOS070MI", "MOS070MIService");
    public final static QName MOS070MIPort = new QName("http://www.tmha.com.au/MOS070MI", "MOS070MIPort");
    static {
        URL url = null;
        try {
            url = new URL(Constants.localWorkspacePath + "MOS070MI.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MOS070MIService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", Constants.localWorkspacePath + "MOS070MI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MOS070MIService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MOS070MIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MOS070MIService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MOS070MIService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MOS070MIService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MOS070MIService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MOS070MI
     */
    @WebEndpoint(name = "MOS070MIPort")
    public MOS070MI getMOS070MIPort() {
        return super.getPort(MOS070MIPort, MOS070MI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MOS070MI
     */
    @WebEndpoint(name = "MOS070MIPort")
    public MOS070MI getMOS070MIPort(WebServiceFeature... features) {
        return super.getPort(MOS070MIPort, MOS070MI.class, features);
    }

}
