
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package au.com.tmha.mos070mi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-02-24T10:22:00.027+11:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "MOS070MIService",
                      portName = "MOS070MIPort",
                      targetNamespace = "http://www.tmha.com.au/MOS070MI",
                      wsdlLocation = "file:/C:/Users/User/workspace/JAXWSEclipse/WebContent/WEB-INF/MOS070MI.wsdl",
                      endpointInterface = "au.com.tmha.mos070mi.MOS070MI")
                      
public class MOS070MIImpl implements MOS070MI {

    private static final Logger LOG = Logger.getLogger(MOS070MIImpl.class.getName());

    /* (non-Javadoc)
     * @see au.com.tmha.mos070mi.MOS070MI#updOperation(au.com.tmha.mos070mi.updoperation.UpdOperationCollection  updOperation )*
     */
    public au.com.tmha.mos070mi.updoperation.UpdOperationResponseCollection updOperation(au.com.tmha.mos070mi.updoperation.UpdOperationCollection updOperation) { 
        LOG.info("Executing operation updOperation");
        System.out.println(updOperation);
        try {
            au.com.tmha.mos070mi.updoperation.UpdOperationResponseCollection _return = new au.com.tmha.mos070mi.updoperation.UpdOperationResponseCollection();
            java.util.List<java.lang.Object> _returnUpdOperationResponseItem = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnUpdOperationResponseItemVal1 = null;
            _returnUpdOperationResponseItem.add(_returnUpdOperationResponseItemVal1);
            _return.getUpdOperationResponseItem().addAll(_returnUpdOperationResponseItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
